version: '3'
services:
  app:
    build:
        context: ./php-apache
        dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "3333:80"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  www:
